import { Selector, ClientFunction } from 'testcafe'
import { TEST_URL, TEST_LOGIN, TEST_PASSWORD } from '../tests.env.json'

fixture('/login').page(TEST_URL)

const getPageUrl = ClientFunction(() => window.location.href)

test('Profile test', async t => {
    await t
        .typeText('#email', TEST_LOGIN)
        .expect(Selector('#email').value).eql(TEST_LOGIN)
        .typeText('#password', TEST_PASSWORD)
        .expect(Selector('#password').value).eql(TEST_PASSWORD)
        .click('#button')
        .expect(Selector('#loading').exists).ok()
        .wait(10000)
        .expect(getPageUrl()).contains('/dashboard')

        .navigateTo(`${TEST_URL}/#/profile`)
        .expect(getPageUrl()).contains('/profile')
        .click('#dashboard')
        .expect(getPageUrl()).contains('/dashboard')

        .navigateTo(`${TEST_URL}/#/profile`)
        .expect(getPageUrl()).contains('/profile')
        .click('#username')
        .pressKey('ctrl+a delete')
        .expect(Selector('#username').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText('#username', 'testadmin')
        .expect(Selector('#username').value).eql('testadmin')
        .click('#email')
        .pressKey('ctrl+a delete')
        .expect(Selector('#email').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText('#email', 'testadmin@provider.com')
        .expect(Selector('#email').value).eql('testadmin@provider.com')
        .click('#phone')
        .pressKey('ctrl+a delete')
        .expect(Selector('#phone').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText('#phone', '11111111111')
        .expect(Selector('#phone').value).eql('(11) 11111-1111')
        .click('#cnpj')
        .pressKey('ctrl+a delete')
        .expect(Selector('#cnpj').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText('#cnpj', '64979879878979')
        .expect(Selector('#cnpj').value).eql('64.979.879.8789-79')
        .click('#name')
        .pressKey('ctrl+a delete')
        .expect(Selector('#name').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText('#name', 'testadmin')
        .expect(Selector('#name').value).eql('testadmin')
        .click('#tradeName')
        .pressKey('ctrl+a delete')
        .expect(Selector('#tradeName').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText('#tradeName', 'testadmin')
        .expect(Selector('#tradeName').value).eql('testadmin')
        .click('#description')
        .pressKey('ctrl+a delete')
        .expect(Selector('#description').value).eql('')
        .click('#save')
        .expect(Selector('#errorMessage').exists).ok()
        .typeText(
            '#description',
            'testadmintestadmintestadmintestadmintestadmintestadmin'
        )
        .click('#save')
        .expect(Selector('#successMessage').exists).ok()

        .click('#number')
        .pressKey('ctrl+a delete')
        .expect(Selector('#number').value).eql('')
        .click('#saveUnit')
        .expect(Selector('#errorMessageUnit').exists).ok()
        .typeText('#number', '1234567891011')
        .expect(Selector('#number').value).eql('1234567891011')
        .click('#unitName')
        .pressKey('ctrl+a delete')
        .expect(Selector('#unitName').value).eql('')
        .click('#saveUnit')
        .expect(Selector('#errorMessageUnit').exists).ok()
        .typeText('#unitName', 'testunit')
        .expect(Selector('#unitName').value).eql('testunit')
        .click('#address')
        .pressKey('ctrl+a delete')
        .expect(Selector('#address').value).eql('')
        .click('#saveUnit')
        .expect(Selector('#errorMessageUnit').exists).ok()
        .typeText('#address', 'testingnow')
        .expect(Selector('#address').value).eql('testingnow')
        .click('#zip')
        .pressKey('ctrl+a delete')
        .expect(Selector('#zip').value).eql('')
        .click('#saveUnit')
        .expect(Selector('#errorMessageUnit').exists).ok()
        .typeText('#zip', '55555555')
        .expect(Selector('#zip').value).eql('55555-555')
        .click('#city')
        .pressKey('ctrl+a delete')
        .expect(Selector('#city').value).eql('')
        .click('#saveUnit')
        .expect(Selector('#errorMessageUnit').exists).ok()
        .typeText('#city', 'testing')
        .expect(Selector('#city').value).eql('testing')
        .click('#state')
        .pressKey('ctrl+a delete')
        .expect(Selector('#state').value).eql('')
        .click('#saveUnit')
        .expect(Selector('#errorMessageUnit').exists).ok()
        .typeText('#state', 'testing')
        .expect(Selector('#state').value).eql('testing')
        .click('#saveUnit')
        .expect(Selector('#successMessageUnit').exists).ok()

        .click('#newDevice')
        .click('#saveDevice')
        .expect(Selector('#errorMessageDevice').exists).ok()
        .typeText('#deviceId', '12345678')
        .expect(Selector('#deviceId').value).eql('12345678')
        .click('#saveDevice')
        .expect(Selector('#errorMessageDevice').exists).ok()
        .click('#deviceId')
        .pressKey('ctrl+a delete')
        .expect(Selector('#deviceId').value).eql('')
        .typeText('#deviceName', 'testing')
        .expect(Selector('#deviceName').value).eql('testing')
        .click('#saveDevice')
        .expect(Selector('#errorMessageDevice').exists).ok()
        .typeText('#deviceId', '12345678')
        .expect(Selector('#deviceId').value).eql('12345678')
        .click('#saveDevice')
        .expect(Selector('#deviceForm0').exists).ok()
        .click('#deviceIdDevicesList0')
        .pressKey('ctrl+a delete')
        .expect(Selector('#deviceIdDevicesList0').value).eql('')
        .click('#saveDevicesList0')
        .expect(Selector('#errorMessageDevicesList').exists).ok()
        .typeText('#deviceIdDevicesList0', '12345678')
        .expect(Selector('#deviceIdDevicesList0').value).eql('12345678')
        .click('#deviceNameDevicesList0')
        .pressKey('ctrl+a delete')
        .expect(Selector('#deviceNameDevicesList0').value).eql('')
        .click('#saveDevicesList0')
        .expect(Selector('#errorMessageDevicesList').exists).ok()
        .typeText('#deviceNameDevicesList0', 'testing')
        .expect(Selector('#deviceNameDevicesList0').value).eql('testing')
        .click('#saveDevicesList0')
        .expect(Selector('#successMessageDevicesList').exists).ok()

        .click('#deleteDevicesList0')
        .click('#not')
        .expect(Selector('#deviceForm0').exists).ok()
        .click('#deleteDevicesList0')
        .click('#yes')
        .expect(Selector('#deviceForm0').exists).notOk()

        .click('#deleteUnit')
        .click('#not')
        .expect(Selector('#consumerUnitForm').exists).ok()
        .click('#deleteUnit')
        .click('#yes')
        .expect(Selector('#consumerUnitForm').exists).notOk()

        .click('#deleteUser')
        .click('#not')
        .expect(Selector('#userForm').exists).ok()
        .click('#deleteUser')
        .click('#yes')
        .expect(getPageUrl()).contains('/login')

})